### ISSUE TITLE
Migrate/close issues from actions/setup-haskell

### ISSUE THREAD

**Issue by jared-w** [haskell/actions#1]
- [ ] include a more fully featured example template? (heres mine!)
- [x] Either use sliding tag or latest tag in README.md
- [x] Bad build of ghc version 8.10.2 for latest on windows ?
- [x] Retry of GHC installation upon failure does not work
- [x] Setting GHC/Cabal versions doesn't work with macOS
- [x] Add ghc 9.0.1
- [ ] I suggest add ~/.local/bin to PATH
- [ ] How to install system libraries on windows?
- [x] ghcup set is not run when the desired ghc version is found in the cache
- [ ] [RFC] Statically linked binaries
- [x] Install fails with "cabal: unrecognized 'user-config' option `-a'"
- [ ] Provide cabal-cache executable
- [ ] Provide `hlint` executable.
- [x] cabal update fails
- [ ] Not Shown in Marketplace

**Comment by cartazio** [comment]
Will the other repo mirror this one going forward?

**Comment by jared-w** [comment]
No, it won't. You'll have to switch to using `haskell/actions/setup` in your workflows, unfortunately
