### ISSUE TITLE
Use `stack-2.7.5` ? 

### ISSUE THREAD

**Issue by andreasabel** [haskell/actions#101]
It is claimed the `latest` for `stack` gives the latest release of stack:
https://github.com/haskell/actions/blob/73693368347a0470e3334f6339ca6f7533eae755/setup/README.md#L178
But empirically, this does not seem to be the case.  (I am getting `2.7.3`.)
So maybe `latest` is really just the _latest in the mental model_ of `haskell/actions/setup` (as opposed to in the real world out there), and this has to be updated (and maybe the ambiguous README line as well)?

**Comment by andreasabel** [comment]
Suppose I add `2.7.5` here: https://github.com/haskell/actions/blob/a53ace849582aa5eec1465dd2b2a18a8b0b10bc9/setup/src/versions.json#L40-L41
Which scripts do I have to run to propagate this to `lib/versions.json` etc.
Is this written somewhere?

**Comment by jared-w** [comment]
I have a branch up that'll fix that soon. If you run `npm install` as you would when developing normally, then the precommit hooks will take care of that.

I'm hoping to get all of that fixed in CI so that it's not necessary to really install anything to make a one line change somewhere.

**Comment by andreasabel** [comment]
Ok, got it: 
- #104

**Comment by jared-w** [comment]
Thanks!
