### ISSUE TITLE
migrate to node 16

### ISSUE THREAD

**Issue by rethab** [haskell/actions#103]
hi @jared-w ,

since all these actions run on node 12 and deprecations warnings will soon start to appear (https://github.com/actions/runner/pull/1735) it might be good to migrate to node 16.

I'll be happy to do the migration -- just let me know :) I see the tsconfig files and some others could use a brush-up as well. Would you accept a PR to do some plumbing?

**Comment by jared-w** [comment]
Absolutely, that would be great. It shouldn't take too long to do the work, and hopefully it won't take much actual updating to do so.
