### ISSUE TITLE
Passing options to hlint-run?

### ISSUE THREAD

**Issue by philderbeast** [haskell/actions#110]
With `hlint-run`, I'm able to pass in folders to this action doing the equivalent of:

```
hlint src/
```

Using the action how would we pass options like `--cpp-define` and `--cpp-simple`?

```
hlint src/ --cpp-define=WINDOWS=1
hlint test/ --cpp-simple
```

https://github.com/commercialhaskell/stack/blob/af098aa6a8246960229871228c5ed757e29916ad/.github/workflows/unit-tests.yml#L24-L26

**Comment by mihaimaruseac** [comment]
@philderbeast can you move this to https://github.com/haskell-actions/hlint-run please? This repo is winding down, the actions got split into separate repos

**Comment by philderbeast** [comment]
Will do, next week.

**Comment by philderbeast** [comment]
@mihaimaruseac it looks like I can't [transfer this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) from `github.com/haskell/actions` to `github.com/haskell-actions/hlint-run` because they are different organisations. Happy to recreate it there and close this one if that is the case.

**Comment by mihaimaruseac** [comment]
Please open one there and close this one.

The idea to opening it yourself instead of us is that this way you will be notified when fixed, as this repo will get disabled, I think.

**Comment by philderbeast** [comment]
Same issue opened as https://github.com/haskell-actions/hlint-run/issues/20.
