### ISSUE TITLE
README mentions non existing version of `haskell/actions/setup`

### ISSUE THREAD

**Issue by coot** [haskell/actions#114]
The [README](https://github.com/haskell/actions/tree/main/setup) mentions `haskell/actions/setup@v2` but it seems the [latest released version](https://github.com/haskell/actions/blob/main/setup/package.json#L3) is `1.2.2`.

**Comment by chshersh** [comment]
I see that this repository actually has all the corresponding tags for version 2:

* https://github.com/haskell/actions/tags

I've been using `v2` in my projects for a while quite successfully:

* https://github.com/chshersh/iris/blob/0b9c50da0a277b298c62064929eb2f875c902841/.github/workflows/ci.yml#L39

**Comment by hazelweakly** [comment]
Yeah, the package.json is actually mostly irrelevant and exists entirely as something I've halfheartedly tried to keep up to sync with the git tags; I'll fix that for real and keep them in sync automatically once I setup some CD to release tags upon successful merging of PRs

Sorry for any confusion there! Github actions relies entirely on tags and so github releases, package.json files, etc., are all things that "don't count" (which isn't particularly intuitive given... how they're used everywhere else)
