### ISSUE TITLE
build fails with /usr/bin/ld.gold: error: cannot find -lgmp

### ISSUE THREAD

**Issue by marc-planard** [haskell/actions#132]
Hello,

I try to build my (quite simple) stack projet. I'm using basicaly the file provided as example, with only the final command modified to fit my needs:
```
> on: [push]
> name: build
> jobs:
>   runhaskell:
>     name: Hello World
>     runs-on: ubuntu-latest # or macOS-latest, or windows-latest
>     steps:
>       - uses: actions/checkout@v3
>       - uses: haskell/actions/setup@v2
>         with:
>           ghc-version: '8.8.4' # Exact version of ghc to use
>           # cabal-version: 'latest'. Omitted, but defaults to 'latest'
>           enable-stack: true
>           stack-version: 'latest'
>       - run: stack build
```

And it fails because it seems to need lib gmp, and I was unable to find any resources indicating how to provide it (maybe my search skills are terrible, I'm very new to github actions).

> Installed GHC.
> [1 of 2] Compiling Main             ( /home/runner/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /home/runner/.stack/setup-exe-src/setup-mPHDZzAJ.o )
> [2 of 2] Compiling StackSetupShim   ( /home/runner/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/runner/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o )
> Linking /home/runner/.stack/setup-exe-cache/x86_64-linux-tinfo6/tmp-Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7 ...
/usr/bin/ld.gold: error: cannot find -lgmp
> /home/runner/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.7/lib/ghc-8.10.7/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_4.c:function integerzmwiredzmin_GHCziIntegerziType_zdwplusBigNatWord_info: error: undefined reference to '__gmpn_add_1'
> ...

Thanks for any clue and I hope I'm not the only one stumbling on this one and that it will help others :)

**Comment by andreasabel** [comment]
>       - run: stack build

This may not use the GHC you installed via `haskell/actions/setup` as specified by `ghc-version`.

`stack` installs its own GHC depending on the snapshot it is used with (look into your `stack.yaml`, the `resolver` field).
You can already see that likely `stack` uses GHC 8.10.7 in your setup:
> Linking /home/runner/.stack/setup-exe-cache/x86_64-linux-tinfo6/tmp-Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7 

That said, a missing `-lgmp` can usually be addressed by installing the GMP library, which is a GHC prerequisite.
If you look at e.g. https://www.haskell.org/ghc/download_ghc_8_8_4.html, you can read stuff like:
> ... It was made on a Debian 9 "Stretch" system and requires GMP 6.0.

**Comment by marc-planard** [comment]
Thanks a lot for your answer (and for reformatting my post, really appreciated).
Unfortunately I may lack basic knowledge or understanding of how github actions (or this particular one) are supposed to work to make good use of your remarks:
* I've downgraded the resolver version in my stack.yml to lts-16.27 (as according to my research it correspond to ghc-8.8.4) : it still tries to install its own ghc and therefor crash on a missing libgmp.
* I've changed my command to "stack --system-ghc build" to try to force it to use the installed ghc and not build its own (which sounds like a good idea resource and time-wise anyway), still crash on a missing libgmp (not sure doing what though, trying compiling cabal?)
    > [1 of 2] Compiling Main             ( /home/runner/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /home/runner/.stack/setup-exe-src/setup-mPHDZzAJ.o )
    > [2 of 2] Compiling StackSetupShim   ( /home/runner/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/runner/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o )
    > Linking /home/runner/.stack/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.4 ...
/usr/bin/ld.gold: error: cannot find -lgmp
* I've tried several method to install libgmp before running stack:
** added "run: sudo apt-get install libgm-dev" before my "run: stack..." line => "E: Unable to locate package libgmp-dev" (bad source.list or no internet access? I have no idea..)
** tried to use "use: awalsh128/cache-apt-pkgs-action@latest" to get libgmp-dev => "08:44:17 Package 'libgmp-dev' not found."

I have no idea where to go from here. I was under the impression that by copy/pasting the "Basic with Stack:" example file from the Readme I will get an environment where I can use stack (I don't understand why this example runs "runhaskell Test.hs" and not a genuine stack usage. Is actually anybody using stack with github actions ?
(I realize this last part may sound snarky or sarcastic but I'm genuinely questioning if it's possible to use github actions with stack, and if yes how...). 

Thanks for you help.

**Comment by andreasabel** [comment]
@marc-planard wrote:
> Is actually anybody using stack with github actions ?

Yes, plenty:
- https://github.com/hackage-trustees/hackage-cli/blob/master/.github/workflows/stack.yml
- https://github.com/haskell/text-icu/blob/master/.github/workflows/cabal-mac-win.yml
- https://github.com/andreasabel/agda2lagda/blob/master/.github/workflows/stack.yml
- https://github.com/agda/agda/blob/master/src/github/workflows/stack.yml

Sorry I tried to look for a simple one, but these workflows always end up complex with special cases for each OS.  Hopefully you can distill something from these examples.

**Comment by andreasabel** [comment]
I hope my links helped resolve your issue.  
Also, there are Haskell chat groups and mailing list where friendly people might provide more guidance.
