### ISSUE TITLE
Splitting this repo into one repo for each action!

### ISSUE THREAD

**Issue by andreasabel** [haskell/actions#141]
It is not customary to host several github actions in one repo.  The reason is simple to understand:
**Versions of an action are identified by tags of the form `v1.2.3`, and such tags apply to the whole repo.**
So basically, bundling several actions into one repo means bundling them into a single versioning scheme.

Putting several actions into one repo **explicitly violates the github marketplace policy** written at https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace (retrieved 2022-12-22):
> Each repository must contain a single action.

So the suggestion is to split this repo into 3, one for each action.

### If stuff should reside in the `haskell` organization

New names for the actions:
- `haskell/setup-action` (or maybe just `haskell/setup`?)
- `haskell/hlint-setup`
- `haskell/hlint-run`

Would be good to get co-ownership of `haskell` then.

### If stuff move to organization `haskell-actions`

New names for the actions:
- `haskell-actions/setup` or `haskell-actions/haskell-setup`
- `haskell-actions/hlint-setup`
- `haskell-actions/hlint-run`

One would have to negotiate co-ownership of the `haskell-actions` orga with @AlexeyRaga then.

See also:
- #89

Prior art (similar concerns than here):
- #18

**Comment by cartazio** [comment]
this sounds like a nice idea to me, what would the suggested workflow for migrating basic build test CI after this change?

**Comment by andreasabel** [comment]
To close this repo down, we could release a new major version here that deactivates the ordinary function of `haskell/actions/setup` (1) and instead errors out with a migration message.
Say, we have migrated the current `setup` action to `haskell/setup-action` (2), we could release a `v3.0.0` in both places, which may not have new functionality at (2), but "destroys" (1).  This would force folks moving to the new major version to also migrate from (1) to (2).  (It would be great if `dependabot` supported such moves.)

**Comment by Kleidukos** [comment]
I'm all for splitting actions into multiple repos if that can help with the versioning. Could we also bring https://github.com/haskell-ci back into the fold?

**Comment by liskin** [comment]
> I'm all for splitting actions into multiple repos if that can help with the versioning. Could we also bring https://github.com/haskell-ci back into the fold?

haskell-ci is not a GitHub Action, though, it's a GitHub Actions workflow generator. Why unify its versioning with an Action (that it doesn't even use)?

**Comment by Kleidukos** [comment]
@liskin I was unclear, sorry. https://github.com/haskell-ci is a separate organisation that further splits the tooling, ACLs, responsibilities and accountability of the tooling. This is the same as https://github.com/haskell-actions btw. We should aim at reducing the surface for collaboration and contribution for this kind of strategic tooling.

**Comment by andreasabel** [comment]
> [@haskell-ci](https://github.com/haskell-ci) is a separate organisation that further splits the ACLs, responsibilities and accountability of the our CI tooling.

@haskell-ci is a CI generator for multiple CI platforms (shell, travis, github) so maybe it does not need to get unified with an organization caring just about github actions.  (E.g., it is thinkable that @haskell-ci will also support gitlab at some point.)

@AlexeyRaga: Would you open up the `haskell-actions` organization for co-ownership by other stakeholders, e.g. the maintainers of this setup action?  (I thought I asked you before, but many only implicitly so, can't find the record now.)

**Comment by Kleidukos** [comment]
> > [@haskell-ci](https://github.com/haskell-ci) is a separate organisation that further splits the ACLs, responsibilities and accountability of the our CI tooling.
> 
> @haskell-CI is a CI generator for multiple CI platforms (shell, travis, github) so maybe it does not need to get unified with an organization caring just about github actions. (E.g., it is thinkable that @haskell-CI will also support gitlab at some point.)
> 

@andreasabel I'm not sure I can see any benefit from splitting the tooling, and I definitely **cannot** see any benefit in separating the actions repositories from the @haskell organisation. I would love to be enlightened though.

**Comment by cartazio** [comment]
if people want to make tooling available that isn't under centralized
administrative control, its totally their prerogative  :)

**Comment by Kleidukos** [comment]
@cartazio and yet it sends the wrong message when these people are also stewards of the community and that these tools have the vocation to be promoted as *the* tool. Without any kind of structure that's how we end up with community standards that become unmaintained because the street cred of one person was enough for ecosystem-wide adoption but there wasn't any succession plan in place, so the bus factor was effectively of 1.

**Comment by Kleidukos** [comment]
Moreover, this will also deprive these different organisations that provide infrastructural services to the ecosystem from benefiting from the very large CI resources that our diplomatic link with GitHub has unlocked for the Haskell organisation.

**Comment by ulysses4ever** [comment]
I'm sorry if I don't really follow the discussion here, and I don't have an opinion about splitting the action into several repos, but I do have one on Haskell-CI. I believe Haskell-CI should be brought as close to the action as possible for a simple reason: it improves visibility. Let me tell you: many beginners and even intermediate Haskell users can find the action but have no idea about Haskell-CI. Having it under the same organization would help with that even if a bit.

**Comment by ulysses4ever** [comment]
Also, I'm for splitting into several repos under a **separate organization**, my reasoning: https://github.com/haskell/actions/pull/228#issuecomment-1494369676

**Comment by Kleidukos** [comment]
@ulysses4ever I understand the argument that it can be more practical to have a separate org for complexity management reasons, however we need to establish a very clear structure in terms of who is accountable to whom. If this is just an unofficial project, it means that we lose a bunch of trust in the tooling there because whoever is involved is free to do whatever they want, and as such haskell.org cannot recommend the GitHub Actions anymore.

Also we must have safeguard mechanisms in case there is a takeover or a series of burn-out that leaves this organisation without any responsive maintainer. The ACLs of this org cannot be an afterthought. :)

**Comment by cartazio** [comment]
Ok cool.  Was just reading that way in my head.

**Comment by ulysses4ever** [comment]
Is it an inherently unsolvable task to create a credible body other than github.com/haskell? It's too bad then because the haskell github org is already overloaded imo. Let me get back to the example of Julia. It has a bunch of organizations for common things:

- https://github.com/JuliaLang for language related things  such as the website, the language implementation, the package manager, juliaup, Jupiter kernel, etc.
- https://github.com/JuliaCI -- benchmarking, various CIs other than GitHub (e.g. buildkite), code coverage
- https://github.com/JuliaTesting -- packages for various kinds of testing

I am not hopeful for anything close to this much of organization (pun intended) but if we can't split out a single github organization that could be perceived as credible enough to be a goto for a common task, I think we need to have a conversation about why this is the case. And that conversion certainly shouldn't happen on this bugtracker.  The governance of the haskell github org itself is a moot point that would benefit from some discussion as well (see https://github.com/haskell/meta/issues/1).

**Comment by cartazio** [comment]
For what it’s worth I suport y’all making your own org centered around this
ci tooling in whatever way makes it easiest for users, current maintainers
and current contributors.  How can I help?

**Comment by Kleidukos** [comment]
@ulysses4ever

> Is it an inherently unsolvable task to create a credible body other than github.com/haskell?

On the contrary, I laid out the things to keep in mind whilst doing so (and I'm sorry that I wasn't clear when I did):

* Get recognition as an official organisation of the Haskell project:
  * Ensure proper communication about this (the Haskell.org committe can handle that aspect);
  * Get included in negotiations with partners when it comes to allocating resources destined for the Haskell project
* Establish clear line of accountability:
  * ACLs that reflect the leadership of the Haskell project;
  * Enforcing the code of conduct of the project to ensure that participants are granted the same rights and duties as in other official spaces;

This is pretty standard stuff, as we don't want to end up in another haskell.org/haskell-lang.org situation.

**Comment by cartazio** [comment]
that sitch was more a fp complete based problem than anything else.

**Comment by Kleidukos** [comment]
No, I'm speaking about the dissolution of legitimacy and accountability.

**Comment by cartazio** [comment]
Anyways: however I can help progress the ci tooling folks efforts , please
let me know.  I want to help out :)

**Comment by Bodigrim** [comment]
> Could we also bring https://github.com/haskell-ci back into the fold?

AFAICT `haskell-ci` has never been a part of Haskell organization, so there is nothing to bring back. FWIW I also read this remark as coercive: "we" cannot (and should not) do anything with an independently maintained package against the will or without consent of respective maintainers, who were not invited to this discussion.

**Comment by Kleidukos** [comment]
I see, much clearer when it's explained.

However I was not implying any kind of takeover or coercive action, and I'm sorry that it came out like that.

**Comment by andreasabel** [comment]
I was hoping to get @haskell-actions on board (@AlexeyRaga). New attempt:
- https://github.com/haskell-actions/hackage-publish/issues/7

If @haskell-actions was opened to major stakeholders in CI, this would be the canonical home.
While we are discussing, I squatted @haskell-gh-actions as an alternative organization name, if it need be.
@haskell is still an option to me, but I am afraid it will get bloated by an unforeseeable number of actions, and we would need a clear naming discipline.  I tend to `haskell/actions-FOO` now as this simulates `haskell/actions/FOO` most directly.

**Comment by andreasabel** [comment]
@newhoggy opened @haskell-actions to new actions and wider collaboration, so I guess this the way to go!
I have redirected PRs with new actions to @haskell-actions.

@Kleidukos wrote:
> * Get recognition as an official organisation of the Haskell project:
>   
>   * Ensure proper communication about this (the Haskell.org committe can handle that aspect);
>   * Get included in negotiations with partners when it comes to allocating resources destined for the Haskell project
> * Establish clear line of accountability:
>   
>   * ACLs that reflect the leadership of the Haskell project;
>   * Enforcing the code of conduct of the project to ensure that participants are granted the same rights and duties as in other official spaces;
> 
> This is pretty standard stuff

Where can I read about these procedures and principles?
Do you have links for (some of) these points?

**Comment by ulysses4ever** [comment]
@andreasabel could this repo (haskell/actions) be archived? It's quite confusing to have two active repos for the same thing...

**Comment by andreasabel** [comment]
> @andreasabel could this repo (haskell/actions) be archived? It's quite confusing to have two active repos for the same thing...

I agree, and eventually, yes.
However, I want to update the setup action with a deprecation warning once the move is complete.  And then maybe start brownouts...
Note that you can still run an action from an archived repository, this is why some are still on `actions/haskell-setup`.

**Comment by Kleidukos** [comment]
@andreasabel Please hit me up when you want the Haskell.org committee to make announcements and publish stuff on our social media accounts :+1:

**Comment by andreasabel** [comment]
@mihaimaruseac Sorry, that comment slipped my attention.  
Great to have you onboard!  I added you to @haskell-actions where you can recreate these actions.

I extracted the `setup` action in a way that preserved the history, using [`git-filter-repo`](https://github.com/newren/git-filter-repo), see also https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository.  Then I git-moved everything from `setup/` to the root in https://github.com/haskell-actions/setup/commit/6459b357f3e9d610896d8649fce2735260086c67 and then made a commit replacing `/setup/` by `/` (and similar) in the CI workflow: https://github.com/haskell-actions/setup/commit/d98a6fbd9580b4528a50c8a5c8e9df17c0f75bdf

**Comment by mihaimaruseac** [comment]
Sorry @andreasabel , now I missed the comment myself. This is great!

**Comment by mihaimaruseac** [comment]
The hlint actions are moved now. Long comment at https://github.com/haskell/actions/pull/301#issuecomment-1722353522

This can be closed now, I think?
