### ISSUE TITLE
Bunch of warnings during setup

### ISSUE THREAD

**Issue by asarkar** [haskell/actions#144]
Step `Run haskell/actions/setup@v2`

```
Run haskell/actions/setup@v2
  with:
    enable-stack: true
    ghc-version: latest
    cabal-version: latest
    stack-version: latest
Preparing to setup a Haskell environment
Resolved latest to 9.4.2
Resolved latest to 3.8.1.0
Resolved latest to 2.9.3
```

Everything says "resolved latest", so, the obvious question is "latest of what?"

Step `Installing ghc version 9.4.2`
```
[ Warn  ] New cabal version available. To upgrade, run 'ghcup install cabal 3.8.1.0'
```

Step "Install HLint`
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

The link above has a hard date for removing `set-output`.
> Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

**Comment by andreasabel** [comment]
> Everything says "resolved latest", so, the obvious question is "latest of what?"

`latest` is resolved according to this file: https://github.com/haskell/actions/blob/main/setup/src/versions.json


> Step "Install HLint`
> 
> ```
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ```

I do not see anyone responsibly maintaining the hlint actions here, so, PRs welcome!

**Comment by asarkar** [comment]
> latest is resolved according to ...

What I meant is that "Resolved latest to 9.4.2" should say what is the latest of what ("latest stack to x"), otherwise, the log statement isn't useful at all, since there are three of them that say the same thing.

**Comment by andreasabel** [comment]
> What I meant is that "Resolved latest to 9.4.2" should say what is the latest of what ("latest stack to x"), otherwise, the log statement isn't useful at all, since there are three of them that say the same thing.

Ah sorry.  Frankly, I didn't see this problem, because I know all the GHC, Cabal, and Stack version numbers by heart, so if I see 3.6.2.0, my brain adds "cabal", and if I see 8.0.2, my brain adds "ghc".

Thanks for clarifying this!

**Comment by andreasabel** [comment]
@asarkar wrote:
> Step `Installing ghc version 9.4.2`
> 
> ```
> [ Warn  ] New cabal version available. To upgrade, run 'ghcup install cabal 3.8.1.0'
> ```
This warning comes from a third party, `ghcup`.  We do not aim to filter warnings by third-party apps.

You can safely ignore this warning.

**Comment by asarkar** [comment]
> @asarkar wrote:
> 
> > Step `Installing ghc version 9.4.2`
> > ```
> > [ Warn  ] New cabal version available. To upgrade, run 'ghcup install cabal 3.8.1.0'
> > ```
> 
> This warning comes from a third party, `ghcup`. We do not aim to filter warnings by third-party apps.
> 
> You can safely ignore this warning.

I wasn’t suggesting hiding the message, as that achieves nothing. I was wondering if you could literally do what the message says, that is, run `ghcup install cabal`

**Comment by andreasabel** [comment]
> I was wondering if you could literally do what the message says, that is, run `ghcup install cabal`

Well, this is what is eventually happening.  But `ghcup` emits this warning as the first thing it does after invocation, so I am afraid you will get to see it anyway.

**Comment by asarkar** [comment]
I’ve opened https://github.com/haskell/actions/issues/149 to track the issue with hlint. If nothing is done it’ll stop working in 6 months, so, it seems reasonable to track the problem separately.
