### ISSUE TITLE
Haddock unable to find documentation for `base` with GHC `9.2.5` and `9.4.4` on Ubuntu

### ISSUE THREAD

**Issue by jonathanknowles** [haskell/actions#176]
Upstream:
- [x] https://github.com/actions/runner-images/pull/6972

Original post:

Hi there!

About 10 days ago (January 13th 2023, to be precise), several of my GitHub repositories (using `haskell/actions/setup@v2`) started reporting _errors_ when building **haddock documentation** with **GHC** **`9.2.5`** and **`9.4.4`** on **Ubuntu**.

In particular, I started seeing the following error after the invocation of `cabal haddock`:
```
Warning: The documentation for the following packages are not installed.
No links will be generated to these packages:
base-4.17.0.0, ghc-bignum-1.3, ghc-prim-0.9.0
```

As a result, generated haddock documentation includes no hyperlinks to functions and modules in the `base` library. (But hyperlinks to other library dependencies are generated just fine!)

## Hypothesis

The `haskell/actions/setup@v2` action, when run with GHC **`9.2.5`** or **`9.4.4`**, is somehow not installing Haddock documentation for the `base` library (or the libraries on which it depends, such as `ghc-prim`).

## Evidence

**On my local machine** (also running Ubuntu), if I use the latest version of `ghcup` (`0.1.19.0`) to install GHC `9.4.4`, the documentation for `base` appears to be installed correctly:

> ```
> $ find ~/.ghcup/ | grep /doc/ | grep /base- | grep /index.html
> /home/jsk/.ghcup/ghc/9.4.4/share/doc/ghc-9.4.4/html/libraries/base-4.17.0.0/index.html
> ...
> ```
> ```
> $ find ~/.ghcup/ | grep /doc/ | grep /base- | wc
> 6605    6605  654898
> ```

Indeed, if I use `cabal haddock` to build documentation on my local machine, then I'm able to generate hyperlinks to `base` without any problems.

**But running the same commands on the GitHub action runner** seems to indicate that the documentation  for `base` is missing:

> ```
> $ find ~/.ghcup/ | grep /doc/ | grep /base- | grep /index.html
> (no output)
> ```
> ```
> find ~/.ghcup/ | grep /doc/ | grep /base- | wc
> 0       0       0
> ```

On the other hand, library files are installed just fine (as expected):

> ```
> find ~/.ghcup/ | grep /lib/ | grep /base- | wc
> 1165    1165  107294
> ```

If I repeat the same experiment (again on a GitHub action runner) with GHC `8.10.7` or GHC `9.0.2`, then I'm unable to replicate the problem: the documentation for `base` is installed in the expected location, and I'm able to generate haddock documentation successfully:

> ```
> $ find ~/.ghcup/ | grep /doc/ | grep /base- | grep /index.html
> /home/runner/.ghcup/ghc/9.0.2/share/doc/ghc-9.0.2/html/libraries/base-4.15.1.0/index.html
> ```
> ```
> $ find ~/.ghcup/ | grep /doc/ | grep /base- | wc
> 777     777   79555
> ```

## Question

Did something change with the way that `haskell/actions/setup@v2` installs GHC (and its bundled documentation) on or around January 13th 2023?

## Links

Here's a link to a GitHub action run that demonstrates the problem:
https://github.com/jonathanknowles/haskell-example/actions/runs/3978681882/jobs/6820602622
(See the "Debugging" and "Documentation (Generation)" jobs.)

Many thanks for your help!

Jonathan

**Comment by andreasabel** [comment]
@jonathanknowles : If you look at what `haskell/action/setup` and ghcup are doing in your run about installing GHC 9.4.4, they is not installing it from scratch, but find it already installed in the virtual environment:
https://github.com/jonathanknowles/haskell-example/actions/runs/3978681882/jobs/6820602622#step:3:18
```
  /opt/hostedtoolcache/ghcup/0.1.19.0/x64/ghcup set ghc 9.4.4
  [ Info  ] GHC 9.4.4 successfully set as default version
  Found ghc 9.4.4 in cache at path /home/runner/.ghcup/ghc/9.4.4/bin. Setup successful.
```
You are given the Ubuntu-22.04 virtual environment in its version 20230118.2 (see https://github.com/jonathanknowles/haskell-example/actions/runs/3978681882/jobs/6820602622#step:1:9).

If I look at your older builds before you worked on fixing the documentation, I can see that GHC 9.4.4 was installed from scratch: https://github.com/jonathanknowles/haskell-example/actions/runs/3919724568/jobs/6700906900#step:3:17
> [ Info  ] downloading: [https://downloads.haskell.org/~ghc/9.4.4/ghc-9.4.4-x86_64-apple-darwin.tar.xz](https://downloads.haskell.org/~ghc/9.4.4/ghc-9.4.4-x86_64-apple-darwin.tar.xz)

This build used the 20221215.1 version of the Ubuntu-22.04 virtual environment: https://github.com/jonathanknowles/haskell-example/actions/runs/3919724568/jobs/6700906900#step:1:9

So, yes, something happened: Upstream updated, with GHC 9.4.4 suddenly shipped with the virtual environment and not installed via ghcup by the setup action.  This may well explain the difference you are seeing.

I don't know how upstream packages GHC, and whether they include the documentation for the core libraries.

If I understand the code of this action correctly, the criterion whether `ghc-9.4.4` is installed is whether this executable exists and nothing else (so it does not check whether the installation comes with all features).

Disclaimer: Doctors can be wrong.  There might be other explanations for the symptoms you are seeing.

**Comment by hasufell** [comment]
This is not an issue with ghcup, but with github virtual images: https://github.com/actions/runner-images/blob/c6393f1f231a4bce8aaeb2665d1312b14271169b/images/linux/scripts/installers/haskell.sh#L34

**Comment by andreasabel** [comment]
@hasufell : Thanks for investigating and reporting this upstream!

**Comment by jonathanknowles** [comment]
@andreasabel Many thanks for your help with analysing this!

I was able to work around the issue with the addition of a "purge" step, that nukes the existing `ghc` installation:

https://github.com/jonathanknowles/haskell-example/blob/ed8660f6ef691559bd0e473eabfbe96e6cd9608e/.github/workflows/build.yml#L38-L44

This workaround allows the `haskell/actions/setup@v2` to re-install GHC in the next build step (this time, with complete documentation for core libraries). The workaround does have the slight disadvantage of increasing overall CI times, but at least it's now possible to build working documentation.

And I see @hasufell has created a PR that hopefully solve this issue for Ubuntu images: https://github.com/actions/runner-images/pull/6972

Many thanks to you too @hasufell!

**Comment by andreasabel** [comment]
@jonathanknowles : Thanks for documenting your workaround!

I'll keep this issue open to raise awareness for the problem.  We might close it once upstream is fixed.

**Comment by andreasabel** [comment]
Fixed upstream.
