### ISSUE TITLE
All install methods for cabal 3.8.1.0 failed

### ISSUE THREAD

**Issue by mrkkrp** [haskell/actions#188]
Most invocations of `haskell/actions/setup` fail for me, see e.g.:

https://github.com/mrkkrp/megaparsec/actions/runs/4132915184/jobs/7148573351

Takes about 10 retries to get it to pass. This started at least yesterday. Not sure what is going on here.

**Comment by andreasabel** [comment]
It is a ghcup failure: https://github.com/mrkkrp/megaparsec/actions/runs/4132915184/jobs/7148573351#step:3:34

For explanation and workaround, please see:
- #187

**Comment by mrkkrp** [comment]
Okay, since you are aware of the problem and it looks like it is only a matter of time til this is fixed (up to 2 weeks  according to the linked post) I think this should be closed.

**Comment by andreasabel** [comment]
Indeed.  But let's keep it open for better visibility.  

(I developed the habit of searching all 4 areas of the quadrant: open and closed issues, open and closed PRs.  But others might just look at the open issues.)

**Comment by andreasabel** [comment]
Seems to have settled down.
