### ISSUE TITLE
Output the path to the stack store

### ISSUE THREAD

**Issue by L-TChen** [haskell/actions#20]
This is another issue related to #12. Similar to the output `cabal-store`, it will be much nicer if this action provides an output for stack global store as well. It makes life easier when setting up a cross-platform CI scripts. 😃

**Comment by andreasabel** [comment]
@L-TChen : Isn't `stack-root` what you are looking for?

**Comment by L-TChen** [comment]
Alright, yes. I think it was documented by 57b808eaaef8f883b7a7bd9b2e31fd31cb2c3e38.
