### ISSUE TITLE
`cabal update` is not run?

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/actions#203]
- [Here's a failing run](https://github.com/haskell/cabal/actions/runs/4400882899/jobs/7706599146)

Not sure if it is related to the recent events like

- #146
- #158

**Comment by andreasabel** [comment]
It looks like `cabal update` _did_ run: https://github.com/haskell/cabal/actions/runs/4400882899/jobs/7706599146#step:4:129
Not sure what the problem is, then.  Maybe two `cabal`s installed in different locations using different homes for storing the package index?  
Can you maybe equip your workflow with extra debug printing, like `which cabal` and the like?

**Comment by ulysses4ever** [comment]
Good idea, thank you: I'll try it. Meanwhile, Mikolaj speculated on IRC that it may be due to the XDG directory switch that cabal is making. Anyway, my experiments so far live here: https://github.com/haskell/cabal/pull/8840

**Comment by Mikolaj** [comment]
I copied the speculation here: https://github.com/haskell/actions/issues/202#issuecomment-1466145088

**Comment by Mikolaj** [comment]
Just to be certain: is the safer order of cache restore (first) vs haskell/setup (second) the default in CI scripts generated by haskell-ci? It seems so, but perhaps there are variations or perhaps I added the cache stanza myself in my scripts I'm looking at?

**Comment by andreasabel** [comment]
@Mikolaj:  Haskell CI currently does things in this order:
1. Install cabal & ghc (via ghcup or apt).
2. Write the `~/.cabal/config` manually (not invoking `cabal`).
3. `cabal update`.
4. Restore `~/.cabal/store`.

But then, it does not generate a CI for Windows, so might not be affected by the XDG.

I am not sure, but I thought that `cabal update` would only affect `~/.cabal/packages` and thus be independent of `~/.cabal/store`.  
One would have to be more careful though if one cached the whole `~/.cabal`, which I would not dare to do with my current superficial knowledge of the `~/.cabal` directory structure.

**Comment by Mikolaj** [comment]
This is good news. Creating ~/.cabal early turns on XDG backward compat mode so there's no risk of mixing up the two locations of cabal index. Thank you.
