### ISSUE TITLE
Choco install of cabal 3.8.1.0 fails

### ISSUE THREAD

**Issue by fendor** [haskell/actions#205]
https://github.com/haskell/hie-bios/actions/runs/4403094451/jobs/7711033046

I am not certain whether this is related to #191, #188 or #201, so I am opening a new issue :)

**Comment by andreasabel** [comment]
@fendor: fixed in `v2`, please try again.

**Comment by andreasabel** [comment]
I consider this fixed, please reopen if necessary.
