### ISSUE TITLE
Determine `outputs.stack-root` via `stack path --stack-root`

### ISSUE THREAD

**Issue by andreasabel** [haskell/actions#215]
https://github.com/haskell/actions/blob/d5d2a76987b2c37320eef82ccc8509ea64c4ff44/setup/README.md?plain=1#L127
It might be simpler and more robust to determine `outputs.stack-root` via `stack path --stack-root`.  Currently:
https://github.com/haskell/actions/blob/d5d2a76987b2c37320eef82ccc8509ea64c4ff44/setup/src/installer.ts#L28-L34

**Comment by sgadkar2** [comment]
hi @andreasabel , I am new to open source contribution. Can you please assign this issue to me.

**Comment by andreasabel** [comment]
Ok, @sgadkar2 , I assigned it to you.   PR welcome!

**Comment by sgadkar2** [comment]
@andreasabel I have raised a pull request. Can you please check if it is correct.

**Comment by andreasabel** [comment]
So after investigation in PR #230 it was agreed not to implement the change suggested in this issue.
