### ISSUE TITLE
hlint-run has build failures with typescript 5.0

### ISSUE THREAD

**Issue by andreasabel** [haskell/actions#227]
With typescript 5.0, `hlint-run` has build failures at these locations:
- https://github.com/haskell/actions/blob/5ad9f8c2edfe8b16e4c10fbe0c4767f6dd30bc5b/hlint-run/src/run.ts#L48
- https://github.com/haskell/actions/blob/5ad9f8c2edfe8b16e4c10fbe0c4767f6dd30bc5b/hlint-run/src/run.ts#L62

https://github.com/haskell/actions/actions/runs/4581184122/jobs/8090527193?pr=223#step:5:7
> Error: src/run.ts(48,39): error TS2365: Operator '>' cannot be applied to types 'string | number' and 'number'.
> Error: src/run.ts(62,41): error TS2365: Operator '>' cannot be applied to types 'string | number' and 'number'.

_Originally posted by @andreasabel in https://github.com/haskell/actions/issues/223#issuecomment-1492859183_

**Comment by andreasabel** [comment]
@rwe : Are you willing to maintain the `hlint` actions here until they have found a new home?  
- Ref: #141

Or should we discontinue them here and point folks back to your repo?

CC @Anton-Latukha .

**Comment by ulysses4ever** [comment]
@andreasabel could you explain how to repro it locally?

**Comment by andreasabel** [comment]
> @andreasabel could you explain how to repro it locally?

Haven't tried to do so.  
(And won't try myself, as I am not maintaining the `hlint`-actions.)

**Comment by ulysses4ever** [comment]
Oh, I'm sorry. And i didn't notice the link to the workflow run: that's enough to repro.

**Comment by ulysses4ever** [comment]
Submitted a fix in https://github.com/haskell/actions/pull/252
