### ISSUE TITLE
Consider license for the entire repository

### ISSUE THREAD

**Issue by chungyc** [haskell/actions#229]
Would it be reasonable for a single license to apply to the entire repository?  Currently, each action has its own license, but there is no license that applies to the repository as a whole.  This means that adding a new action or any code not specifically tied to an action would not be under an open source license, unless they add one on their own.

Fortunately, all the existing actions are under the MIT license, so using it as the overall license would keep the licensing terms consistent, even if the individual LICENSE files would have to remain in order to keep the copyright notices around.

This is in the context of https://github.com/haskell/actions/pull/228, where I would like to propose a new GitHub code scanning action at some point.

**Comment by andreasabel** [comment]
I think a single repo with several actions for different topics (like `setup` and `hlint-*`) does not make much sense, we need a reorganization:
- #141
