### ISSUE TITLE
Support GHC 9.4.5

### ISSUE THREAD

**Issue by andreasabel** [haskell/actions#232]
Dependencies:
- [ ] Windows/Choco: https://github.com/Mistuke/GhcChoco/issues/21

Using GHCup?
- [x] #206

**Comment by lierdakil** [comment]
:thinking: why don't you use ghcup for Windows as well?

**Comment by andreasabel** [comment]
> 🤔 why don't you use ghcup for Windows as well?

This is WIP #206, currently experiencing a regression: 
- [ ] https://github.com/haskell/ghcup-hs/issues/823
