### ISSUE TITLE
Unable to process command '::add-path::/opt/ghc/8.6.5/bin' successfully.

### ISSUE THREAD

**Issue by jrp2014** [haskell/actions#25]
```uses: actions/setup-haskell@v1.1```  leads to 

```The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/```

Should I be using some different version of `setup-haskell`?

**Comment by jared-w** [comment]
You should be using `haskell/actions/setup@v1`, instead. `v1.1` on setup-haskell was kept back by accident so it doesn't contain the latest code; in addition, the actions/setup-haskell repository was archived and moved here. Hence the rename to `haskell/actions/setup`

**Comment by jrp2014** [comment]
Thanks
