### ISSUE TITLE
GHC 8.10.3

### ISSUE THREAD

**Issue by jrp2014** [haskell/actions#26]
For some reason "latest" seems to point to ghc-8.10.2 on Windows.  The latest chocolatey version is 8.10.3 and seems to fix some Windows issues.  Do I need to do anything to get it?

**Comment by jared-w** [comment]
Latest points to GHC 8.10.2 because I was waiting for a few things to get uploaded to various places and haven't had time to immediately address things this past week. It should be fixed semi shortly, but in the meantime just setting the ghc version to 8.10.3 should work.

**Comment by jrp2014** [comment]
Thanks

**Comment by jared-w** [comment]
I updated the tags, so it should be working now. (I forgot to do so last night. Eventually I'll get some spare time to add auto tagging on merge to main.)

**Comment by ndmitchell** [comment]
From what I can tell, with a run I just made, it's still 8.10.2: https://github.com/ndmitchell/hlint/pull/1186/checks?check_run_id=1765192224 - should it have filtered through by now?

**Comment by jared-w** [comment]
Try with `haskell/actions/setup@v1` instead of `actions/haskell-setup@v1`l

I do wish I had been able to get a warning added to the output before the `actions/haskell-setup repository was archived... It's caused no end of downstream pain to have the repository moved underneath people.

**Comment by ndmitchell** [comment]
Thanks for the tip @jared-w - it is indeed a shame that you never got to warn about it - if not for this comment here I'd have probably been on `actions/haskell-setup` for a very long time to come.
