### ISSUE TITLE
When cabal specified as 3.10, setup tries to install cabal 3.1, which fails

### ISSUE THREAD

**Issue by jhrcek** [haskell/actions#267]
When I specify cabal version as 3.10

It seems that setup actions is trying to install cabal version 3.1, which predictably fails.

Here's a relevant part of github actions config (note 3.10 version of cabal)
![Screenshot from 2023-06-29 08-58-14](https://github.com/haskell/actions/assets/2716069/d0945006-0f7c-48ef-80d5-6e868441247b)

But then the job fails, with this error (why is it trying to install cabal 3.1?)

![Screenshot from 2023-06-29 08-57-19](https://github.com/haskell/actions/assets/2716069/a4af0dcd-4bfe-4309-8abb-e9d1efd5ec42)

There is a workaround, namely declaring cabal version as 3.10.1.0.  But it would be nice if the shorter version also worked..

**Comment by TravisCardwell** [comment]
This sounds like a YAML/JSON parsing issue, where `3.10` is being read as a number.  Try string syntax instead:

```yaml
cabal: ["3.10"]
```

**Comment by jhrcek** [comment]
That didn't occur to me. You're right, quoting the number fixed the issue. Thanks!
