### ISSUE TITLE
latest cabal-install version

### ISSUE THREAD

**Issue by juhp** [haskell/actions#28]
IMO this is a  github actions/virtual-environments issue (so I opened actions/virtual-environments#2458 there)
but I thought better to discuss and coordinate here too.

The problem for me is that the github Actions ubuntu runner images are installing the latest cabal-install package
from hvr's ppa but it seems here cabal-install latest is 3.2.0.0: so this makes things a bit confusing:
eg even if one does not set a cabal-install explicitly there is still a Warning about downloading 3.2.

Based on that I have suggested in the above issue that upstream changes the ubuntu images to use the current
stable 3.2.0.0 release instead (instead of the latest 3.4 RC package build).

(Similarly they take latest ghc to be 8.10.3 - lucky there is no 9.0 yet in the ppa - but there will be before long I suppose .;-)
Overall I don't think the "just take the latest version" solution is very good - though of course it reduces their PR churn.
Another approach would be not to install either in the ubuntu images, but then the default latest versions would always need to be installed (not sure how many people just use to the latest image versions only though...).

**Comment by andreasabel** [comment]
I think this was fixed upstream.
