### ISSUE TITLE
cabal v3.10.2 already installed

### ISSUE THREAD

**Issue by newhoggy** [haskell/actions#305]
On Windows specifying a cabal version fails like this:

![Screenshot 2024-01-05 at 6 45 46 pm](https://github.com/haskell/actions/assets/63014/41fb05d6-2b40-44e4-8d3c-aa74a143ee7c)

**Comment by andreasabel** [comment]
haskell/actions/setup@v1 is unsupported, since quite a while already.

Please use `haskell-actions/setup@v2` or `...@latest` (also observe dash-for-slash).
