### ISSUE TITLE
Intermittent "cannot find the file specified" on Windows

### ISSUE THREAD

**Issue by Bodigrim** [haskell/actions#36]
I thought I saw this reported, but cannot find a ticket, so sorry if it is a duplicate. 

After the latest update every other Windows build (cabal + GHC 9.0) fails with 
```
C:\Users\RUNNER~1\AppData\Local\Temp\ghcB4EF.o.tmp: renameFile:renamePath:MoveFileEx "\\\\?\\C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\ghcB4EF.o.tmp" Just "\\\\?\\C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\ghcB4EF.o": does not exist (The system cannot find the file specified.)
```
https://github.com/haskell/bytestring/runs/1874357129?check_suite_focus=true#step:6:195
https://github.com/haskell/bytestring/blob/master/.github/workflows/ci.yml#L56

Rerunning usually helps, so it is not a blocker, just a nuisance.

**Comment by Bodigrim** [comment]
@jared-w any suggestions about this? It plagues roughly half of our Windows builds, e. g., https://github.com/haskell/bytestring/runs/2624677212#step:6:67, and I honestly lost count of rerunning CI over and over again. This did not use to happen with GHC 8.10.

**Comment by tfausak** [comment]
This frequently happens to me as well. Here's the latest example: https://github.com/tfausak/argo/runs/3921022504?check_suite_focus=true#step:11:42

As you said, re-running the build normally fixes it.

**Comment by jared-w** [comment]
I investigated this some more and ran into https://gitlab.haskell.org/ghc/ghc/-/issues/16450, only to find out that @Bodigrim was quite ahead of me and replied there a few days ago :)

Unfortunately, I haven't the slightest idea what's wrong here.

---

@tfausak, it _did_ occur to me that your `TEMP` fix only overwrote `TEMP` and not both `TEMP` and `TMP`.

```yaml
- run: |
    echo "TEMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV
    echo "TMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV
```

Does adding _both_ env variables before using `haskell/actions/setup` resolve the issue? GHC 9.2.1 is also available on Windows now if you feel up for giving that a go.

**Comment by tfausak** [comment]
I haven't seen a random Windows build failure in a while. I'm not sure what changed.

**Comment by jared-w** [comment]
huh, neat. Glad I could fix it 😛

I'm going to go ahead and close this issue then, because it's not something I can fix.
