### ISSUE TITLE
Support GHC 8.10.4

### ISSUE THREAD

**Issue by expipiplus1** [haskell/actions#38]
Thanks for this great resource!

It would be very cool if 8.10.4 were to be supported here.

I wonder how feasible it would be to have some automated updates of supported GHC versions, at the moment it *seems* as though it's a largely manual affair.

**Comment by sorki** [comment]
Seems to work for me, see https://github.com/sorki/haskell-project-template/pull/1

I wonder what would be a good source for automated updates.

**Comment by jared-w** [comment]
I'd like to have automatic updates eventually. For now they're still manual although it's largely condensed into very minimal changes so it's possible that a github workflow could check for updates nightly somehow. (The main reason for the manualness is that the "officially supported versions" in the action are the minimal subset of versions available on linux, macos, and windows [so, practically speaking, ghcup and chocolatey] and I don't know if it's possible to cross check all versions in a OS agnostic way.

**Comment by expipiplus1** [comment]
Thanks!
