### ISSUE TITLE
Can the "not found in cache" warning be downgraded to debug level?

### ISSUE THREAD

**Issue by Rufflewind** [haskell/actions#46]
Is this warning actionable? If not, can it be downgraded to a [`core.debug`]((https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-debug-message)) message?

Source code that generates this warning: https://github.com/haskell/actions/blob/main/setup/src/installer.ts#L56-L63

Example:

> ghc 8.10.3 was not found in the cache. It will be downloaded. If this is unexpected, please check if version 8.10.3 is pre-installed. The list of pre-installed versions is available here: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners The above list follows a common haskell convention that the three latest major releases of ghc are commonly supported. If the list is outdated, please file an issue here: https://github.com/actions/virtual-environments by using the appropriate tool request template: https://github.com/actions/virtual-environments/issues/new/choose

**Comment by jared-w** [comment]
Yeah, it was intended to be a rare occurrence but there seem to be near perpetual mismatches between, say, cabal versions and whatnot. So I'll make it a debug level message and sneak the change into #49
