### ISSUE TITLE
Support new installation path for GHC 9.x on Windows

### ISSUE THREAD

**Issue by maxim-lobanov** [haskell/actions#47]
Hello! I am writing on behalf of maintainers of Hosted GItHub Actions images.

We have noticed that GHC choco package has changed installation path for GHC 9.x on Windows.
Previously, it was installed like `C:\ProgramData\chocolatey\lib\ghc.9.0.1\tools`, currently, `C:\tools`

See package changes: [version 8.4](https://github.com/Mistuke/GhcChoco/blob/master/8.8.4a/ghc/tools/chocolateyInstall.ps1#L25) vs [version 9.0.1](https://github.com/Mistuke/GhcChoco/blob/master/9.0.1/ghc/tools/chocolateyInstall.ps1#L37).

So this task is not able to install GHC 9.x in runtime or consume pre-installed version because this task uses [hardcoded path](https://github.com/haskell/actions/blob/main/setup/src/installer.ts#L231).
This task even won't be able to install GHC 9.x in runtime because it checks installation path after installation.
The new location is `c:\tools\ghc-9.0.1\bin\ghc.exe`

**Comment by maxim-lobanov** [comment]
@jared-w, JFYI

**Comment by maxim-lobanov** [comment]
@jared-w , I have contributed to fix it #48

**Comment by amesgen** [comment]
@maxim-lobanov JFYI, I also fixed this in #44, with a slightly different approach. Not sure which one is "better", I would be happy with both of them.
