### ISSUE TITLE
Link to HPC Codecov Action

### ISSUE THREAD

**Issue by emilypi** [haskell/actions#56]
Hi All,

I think it would be good to work with the folks over at https://github.com/8c6794b6/hpc-codecov to provide a variant on haskell actions that provide code coverage support and integration with codecov.io. What do you think?

They already have an action at https://github.com/marketplace/actions/hpc-codecov-action that was actually pretty hard to find!

**Comment by andreasabel** [comment]
@emilypi : Great suggestion.  Technically though, I think one repo should only contain one action, see:
- #141

**Comment by andreasabel** [comment]
Because of #141, I think the easiest would be to refer to the existing action in our README, so it is easier to find.

**Comment by andreasabel** [comment]
No one picked this issue up in almost 2 years, so I am closing it now.
