### ISSUE TITLE
Consider ghcup for windows

### ISSUE THREAD

**Issue by hasufell** [haskell/actions#70]
Right now, when I define

```yml
jobs:
  build-cabal:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.10.7', '9.0.1']
        cabal: ['3.4.0.0']
```

This will fail on windows only, because `8.10.7` isn't in choco yet. It's quite confusing, because different installers with different release schedules are used under the hood.

I merged https://gitlab.haskell.org/haskell/ghcup-hs/-/merge_requests/159 which would allow the installation procedure on windows to be:

```ps
curl.exe -O https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1
.\bootstrap-haskell.ps1 -InstallDir 'C:\' -InBash -Minimal
```

Leaving you with an msys2 installation (in `C:\ghcup\msys64`) and the ghcup binary (in `C:\ghcup\bin`), nothing more.

Installations of msys2 packages would be carried out via:

```ps
C:\ghcup\msys64\usr\bin\bash.exe -lc 'pacman --noconfirm -S package'
```

**Comment by hasufell** [comment]
Here's an example workflow:

* https://github.com/hasufell/shortbytestring/pull/2/commits/75c18c250e74e674e9a8af8f934457706b0c2fda#diff-c09cc8dc973415b1221308559b96942a1c4b872e690bf360fc22d9b42822d519R28
* https://github.com/hasufell/shortbytestring/runs/3460780761?check_suite_focus=true

**Comment by jared-w** [comment]
I think the windows images from GitHub still use chocolatey under the hood, so I would still default to that (for fastest setup time in the cloud), but I'm looking forward to being able to fall back to ghcup on Windows and possibly even switch to using it first if the action images start using ghcup for windows too.

PRs are more than welcome for the functionality, but otherwise I'll try to get around to it when time permits over the next few weeks :)

**Comment by hasufell** [comment]
> for fastest setup time in the cloud

Good point. I timed that and from my tests ghcup is twice as fast: https://github.com/hasufell/shortbytestring/runs/3487178253?check_suite_focus=true#step:3:1

Takes 2m5s and installs ghcup, cabal, ghc and msys2

```ps1
      Set-ExecutionPolicy Bypass -Scope Process -Force;[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-WebRequest https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1 -UseBasicParsing))) -ArgumentList $false 
```

Takes 3m59s and installs cabal, ghc and msys2

```ps1
    choco install -y haskell-dev 
```

----

Does the haskell action do anything different that would make chocolatey faster?

**Comment by jneira** [comment]
> I think the windows images from GitHub still use chocolatey under the hood,

confirmed: https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-Haskell.ps1

linux/macos uses the package manager (ppa/hvr) for ghc and ghcup for cabal, it seems the ghc installed by ghcup is bigger than the other one (???):

```shell
# We are using apt-get to install ghc, not ghcup,
# because ghc installed through ghcup takes up too much disk space (2GB versus 1GB through apt-get)
```

https://github.com/actions/virtual-environments/blob/ec9ac010f114131adacb246cf87c8127c19aa0d9/images/linux/scripts/installers/haskell.sh#L33

I think @maerwald would find that interesting :wink:

**Comment by hasufell** [comment]
> linux/macos uses the package manager (ppa/hvr) for ghc and ghcup for cabal, it seems the ghc installed by ghcup is bigger than the other one (???):

I'm not sure how that's relevant to the windows discussion?

(The reason is that the apt repository has debug symbols and documentation separate. The GHC build system doesn't allow that split. It has to be done manually.)

**Comment by jneira** [comment]
> I'm not sure how that's relevant to the windows discussion?

Well if linux/macos already would use ghcup for ghc (even as fallback) it would be more appealing for gha unify all the three os's through ghcup

**Comment by jneira** [comment]
In fact upstreaming the actual haskell actions ghc/cabal/stack setup logic to gha vms would be great by itself

**Comment by hasufell** [comment]
> Well if linux/macos already would use ghcup for ghc (even as fallback) it would be more appealing for gha unify all the three os's through ghcup

I don't understand. I thought `haskell/actions` already does use ghcup for linux and mac. I have no idea about `actions/virtual-environments` and currently don't have plans to use it. This ticket is about this action only.

**Comment by jneira** [comment]
hmm `actions/virtual-environments` are the actual vms where gha (so `haskell/actions`) are being run. Afaik (maybe @jared-w could correct me if i am wrong) those vms have already installed the haskell toolchain and `haskell/actions` does a fallback over such preinstalled toolchain (as it can be obsolete for some time)

but yeah we can ignore upstream :slightly_smiling_face:

**Comment by hasufell** [comment]
> hmm actions/virtual-environments are the actual vms where gha (so haskell/actions) are being run.

Ah. I wasn't aware. Well, then my suggestion is to simply tell ghcup where the pre-installed msys2 is. Then the installation will take only a couple of seconds.

**Comment by jneira** [comment]
> as it can be obsolete for some time

Also it does not install all ghc versions, only `2 latest Haskell Major.Minor versions` so haskell/action installs the other ones if requested. But the build would be faster if you use the preinstalled ones and they will be more up to date if they use ghcup :-)

**Comment by hasufell** [comment]
So we can use the pre-installed msys2 via:

```ps1
Set-ExecutionPolicy Bypass -Scope Process -Force;[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-WebRequest https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1 -UseBasicParsing))) -ArgumentList $false, $true, $true, $false, $false, $false, $false, C:\, "", C:\msys64, C:\cabal
```

This takes 15 seconds to install ghcup: https://github.com/hasufell/shortbytestring/runs/3506845639?check_suite_focus=true#step:3:1

**Comment by hasufell** [comment]
https://github.com/actions/virtual-environments/pull/4016

**Comment by newhoggy** [comment]
Also worth considering that Chocolatey is fairly unreliable.  For example, I just witnessed this failure on Windows:

```
Run haskell/actions/setup@v1
Preparing to setup a Haskell environment
Installing ghc version 8.10.4
  Attempting to install ghc 8.10.4 using chocolatey
  ::stop-commands::SetupHaskellStopCommands
  C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe choco install ghc --version 8.10.4 -m --no-progress -r
  Installing the following packages:
  ghc
  By installing you accept licenses for the packages.
  [NuGet] Could not connect to the feed specified at 'https://community.chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.
  ghc not installed. An error occurred during installation:
   Unable to resolve dependency 'cabal (≥ 3.2.0.0)'.
  ghc package files install completed. Performing other installation steps.
  The install of ghc was NOT successful.
  ghc not installed. An error occurred during installation:
   Unable to resolve dependency 'cabal (≥ 3.2.0.0)'.
  
  Chocolatey installed 0/1 packages. 1 packages failed.
   See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
  
  Failures
   - ghc (exited 1) - ghc not installed. An error occurred during installation:
   Unable to resolve dependency 'cabal (≥ 3.2.0.0)'.
  C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe choco install ghc --version 8.10.4 -m --no-progress -r --pre
  Installing the following packages:
  ghc
  By installing you accept licenses for the packages.
  ghc not installed. An error occurred during installation:
   The operation has timed out
  ghc package files install completed. Performing other installation steps.
  The install of ghc was NOT successful.
  ghc not installed. An error occurred during installation:
   The operation has timed out
  
  Chocolatey installed 0/1 packages. 1 packages failed.
   See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
  
  Failures
   - ghc (exited 1) - ghc not installed. An error occurred during installation:
   The operation has timed out
  ::SetupHaskellStopCommands::
Error: All install methods for ghc 8.10.4 failed
```

Reliability trumps installation speed in CI.

**Comment by jneira** [comment]
yeah in hls we experienced that issue with choco lately 😕

**Comment by hasufell** [comment]
So this has been merged upstream at `actions/virtual-environments`:

1. ghcup is used on ubuntu
2. profiling libs and share folder are removed to reduce disk size
3. ghcup is intalled on windows per default (but chocolatey still installs GHCs)

**Comment by newhoggy** [comment]
@hasufell How do I use the `ghcup` installed on Windows by default?

![image](https://user-images.githubusercontent.com/63014/134763319-4479ce4e-24ae-4f60-a262-9309fc4108bd.png)

**Comment by hasufell** [comment]
> @hasufell How do I use the `ghcup` installed on Windows by default?
> 
> ![image](https://user-images.githubusercontent.com/63014/134763319-4479ce4e-24ae-4f60-a262-9309fc4108bd.png)
> 

Hmm, maybe the PATH update didn't make it: https://github.com/actions/virtual-environments/commit/a9ac553edd63658e5309424dffa1819dc386ea28

GHCup on windows is installed usually at `C:\\ghcup\\bin`. 

Furthermore, the script should have set `GHCUP_MSYS2=C:\\msys64` and `CABAL_DIR=C:\\msys64`. If that didn't happen, then there's a problem with the image. Maybe it doesn't run `refreshenv`?

**Comment by newhoggy** [comment]
I don't see those environment variables either.

**Comment by hasufell** [comment]
> I don't see those environment variables either.

Can you try without haskell actions?

**Comment by newhoggy** [comment]
I do see the binary installed at the location you specified:

![image](https://user-images.githubusercontent.com/63014/134764209-8270fb58-5454-472c-a3ec-42bbcaf9253e.png)

**Comment by newhoggy** [comment]
It's the same without Haskell actions.

**Comment by newhoggy** [comment]
Is there a way I can run `refreshenv` myself from within Github Actions?

**Comment by hasufell** [comment]
I'll have to investigate

**Comment by newhoggy** [comment]
@hasufell , do you know of a way I can get the cabal directory that `cabal` installed by `ghcup` on Github Actions would use?  This is necessary for caching the cabal store.

**Comment by newhoggy** [comment]
Ah, yes, I see `CABAL_DIR` defined in the PR you submitted.  Thanks for this!

**Comment by hasufell** [comment]
ghcup is now pre-installed on windows machines as well and should be in PATH etc.

**Comment by newhoggy** [comment]
This is amazing.  Thanks!

**Comment by andreasabel** [comment]
@jared-w : Do you think the time is ripe for switching to `ghcup` under Windows?  
I am trying to bump my CIs to GHC 9.2.2 and they fail on Windows because chocolatey does not have GHC 9.2.1 yet (but ghcup has it!).

**Comment by jneira** [comment]
Some times choco had the new version before ghcup :wink: . I usually open an issue in https://github.com/Mistuke/GhcChoco/issues/18 and usually @Mistuke adds it very quickly.

But afaics 9.2.1 was added to chocolatey: https://community.chocolatey.org/packages/ghc
9.2.2 is not and i guess it will not, as it is broken for windows

**Comment by hasufell** [comment]
> 9.2.2 is not and i guess it will not, as it is broken for windows

Yes: https://gitlab.haskell.org/ghc/ghc/-/issues/21196

**Comment by Mistuke** [comment]
> Some times choco had the new version before ghcup 😉 . I usually open an issue in [Mistuke/GhcChoco#18](https://github.com/Mistuke/GhcChoco/issues/18) and usually @Mistuke adds it very quickly when it is not.
> 

Yes it's coming. I'm just adding a workaround for the broken packaging. I tend to not like to push broken compilers :)

**Comment by hasufell** [comment]
> I tend to not like to push broken compilers :)

Many GHC releases are defunct on one platform or another. E.g. M1 is broken on most GHC versions. I don't do downstream patching.

**Comment by Mistuke** [comment]
> > I tend to not like to push broken compilers :)
> 
> Many GHC releases are defunct on one platform or another. E.g. M1 is broken on most GHC versions. I don't do downstream patching.

That's fine :) I have routinely worked around broken packaging and will continue to do so.

**Comment by hasufell** [comment]
> > > I tend to not like to push broken compilers :)
> > 
> > 
> > Many GHC releases are defunct on one platform or another. E.g. M1 is broken on most GHC versions. I don't do downstream patching.
> 
> That's fine :) I have routinely worked around broken packaging and will continue to do so.

Hopefully that won't be required soon anymore, since GHC should have some dogfood tests as you suggested in the ticket.

I've also offered my help of testing releases manually before they are announced via ghcup, since this is probably the 3rd time I've discovered such issues close after release. But GHC devs decided against human testing.

**Comment by hasufell** [comment]
@andreasabel 

Btw... ghcup is pre-installed on *all* github environments, so this should work on all platforms without `haskell/actions`:

```yml
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.0.2', '8.2.2', '8.4.4', '8.6.5', '8.8.4', '8.10.7', '9.0.2', '9.2.1']
        cabal: ['3.6.2.0']

    steps:
    - name: Install ghc/cabal
      run: |
        ghcup install ghc --set ${{ matrix.ghc }}
        ghcup install cabal ${{ matrix.cabal }}
      shell: bash
```

And in fact, that's what I do in filepath: https://github.com/haskell/filepath/blob/4638d2a6a375064c270fd0a3e249d922859b4f9b/.github/workflows/test.yaml#L58

**Comment by jneira** [comment]
I still think use ghcup in this action would make sense. You can also use chocolatey or hvr/ppa outside this action but it allows workflows abstract away from the concrete channels and the future changes in them.
It will make handling across all os's more uniform.

**Comment by andreasabel** [comment]
@hasufell
> And in fact, that's what I do in filepath: [haskell/filepath@`4638d2a`/.github/workflows/test.yaml#L58](https://github.com/haskell/filepath/blob/4638d2a6a375064c270fd0a3e249d922859b4f9b/.github/workflows/test.yaml#L58)

This CI does not demonstrate caching of dependencies.  How do communicate the cabal store directory in a stable way without `setup-haskell`? 
This would be a typical caching phase:
```
    - uses: actions/cache@v2
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        # The file `plan.json` contains the build information.
        key: ${{ runner.os }}-${{ env.GHC_VER }}-${{ env.CABAL_VER }}-${{ hashFiles('**/plan.json') }}
```

**Comment by newhoggy** [comment]
I feel like `cabal` should have a command to print where the cabal store is since it already knows where it is.

**Comment by andreasabel** [comment]
> I feel like `cabal` should have a command to print where the cabal store is since it already knows where it is.

Is there already a cabal issue for this?  If not please report, linking here!

**Comment by jneira** [comment]
It seems to me that the incoming `cabal status` could give that info: https://github.com/haskell/cabal/pull/7500

An usual workaround is tell cabal use a specific store dir, changing the global config using `cabal init` and use that specific path in the cache step. Not ideal but you have to do it for windows anyways.
https://github.com/haskell/cabal/blob/906a8bcabc307c6c607cf1b9826a6b329e3ceb7f/.github/workflows/windows.yml#L37

**Comment by hasufell** [comment]
> @hasufell
> 
> > And in fact, that's what I do in filepath: [haskell/filepath@`4638d2a`/.github/workflows/test.yaml#L58](https://github.com/haskell/filepath/blob/4638d2a6a375064c270fd0a3e249d922859b4f9b/.github/workflows/test.yaml#L58)
> 
> This CI does not demonstrate caching of dependencies. How do communicate the cabal store directory in a stable way without `setup-haskell`? This would be a typical caching phase:
> 
> ```
>     - uses: actions/cache@v2
>       with:
>         path: ${{ steps.setup-haskell.outputs.cabal-store }}
>         # The file `plan.json` contains the build information.
>         key: ${{ runner.os }}-${{ env.GHC_VER }}-${{ env.CABAL_VER }}-${{ hashFiles('**/plan.json') }}
> ```

I would actually suggest using https://github.com/haskell-works/cabal-cache ...it allows syncing to a directory (instead of S3). Then you would tell `actions/cache@v2` to just cache that directory. That may also save some cache space, because it only caches the needed libraries from the resolution.

I can code up an example if I have a bit more time.

**Comment by andreasabel** [comment]
Work on this is going on in a fork: https://github.com/haskell/actions/compare/main...wz1000:actions:wip/783

**Comment by andreasabel** [comment]
WIP PR:
- #206
