### ISSUE TITLE
setup action fails to set the required ghc version as default

### ISSUE THREAD

**Issue by jneira** [haskell/actions#73]
* Consider this recent workflow: https://github.com/jneira/haskell-language-server/runs/3608526677?check_suite_focus=true

```
Run haskell/actions/setup@v1
  with:
    ghc-version: 8.8.4
    cabal-version: 3.4
    stack-version: latest
Preparing to setup a Haskell environment
Resolved 3.4 to 3.4.0.0
Installing ghc version 8.8.4
  Attempting to install ghc 8.8.4 using apt-get
  /usr/bin/sudo -- sh -c add-apt-repository -y ppa:hvr/ghc && apt-get update && apt-get -y install ghc-8.8.4
.........
  Selecting previously unselected package ghc-8.8.4.
  Preparing to unpack .../ghc-8.8.4_8.8.4-17~20.04_amd64.deb ...
  Unpacking ghc-8.8.4 (8.8.4-17~20.04) ...
  Setting up libncursesw5:amd64 (6.2-0ubuntu2) ...
  Setting up ghc-8.8.4 (8.8.4-17~20.04) ...
  update-alternatives: using /opt/ghc/bin/ghc-8.8.4 to provide /opt/ghc/bin/ghc (opt-ghc) in auto mode
  Processing triggers for libc-bin (2.31-0ubuntu9.2) ...

Found ghc 8.8.4 in cache at path /opt/ghc/8.8.4/bin. Setup successful.
```

* And this info about ghc:

```
Run which cabal
  which cabal
  cabal --version
  which ghc
  ghc --version
  cabal exec ghc -- --version
  shell: /usr/bin/bash -e {0}
/home/runner/.ghcup/bin/cabal
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 
/home/runner/.ghcup/bin/ghc
The Glorious Glasgow Haskell Compilation System, version 9.0.1
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: ghcide-1.4.2.0 (user goal)
[__1] trying: base-4.15.0.0/installed-4.15.0.0 (dependency of ghcide)
[__2] trying: hls-brittany-plugin-1.0.1.0 (user goal)
[__3] next goal: czipwith (dependency of hls-brittany-plugin)
[__3] rejecting: czipwith-1.0.1.3 (conflict:
base==4.15.0.0/installed-4.15.0.0, czipwith => base>=4.11 && <4.15)
[__3] skipping: czipwith-1.0.1.2, czipwith-1.0.1.1, czipwith-1.0.1.0,
czipwith-1.0.0.0 (has the same characteristics that caused the previous
version to fail: excludes 'base' version 4.15.0.0)
[__3] fail (backjumping, conflict set: base, czipwith, hls-brittany-plugin)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: ghcide, base, czipwith,
hls-brittany-plugin
Try running with --minimize-conflict-set to improve the error message.
```

* So although the action is installing/setting ghc-8.8.4 in `/opt/ghc/8.8.4/bin` the ghc in path is 9.0.1 from ghcup (`/home/runner/.ghcup/bin/ghc`)
* It seems it could be related with the recent changes in the setup upstream: https://github.com/actions/virtual-environments/commit/ee69b89103cee75483f6ed348e1c307129a20c8c
  * It dropped hvr/ppp from ghc install and use ghcup exclusively
  * The image with this change was released 2 days ago
    * https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210913.1
    * https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20210913.1   
* I am afraid that it could potentially break all workflows using haskell/actions/setup to set the default ghc :worried: 
* The fix could be make the action be in sync with upstream and use ghcup as unique or first installation method
* The workaround is add a step to make ghcup set the desired ghc version with `ghcup install ghc ${{ matrix.ghc }} --set` (https://github.com/jneira/haskell-language-server/commit/c76c2d0de23f5d504141829522ea9ad142377990)

//cc @jared-w @hasufell

**Comment by jneira** [comment]
>     * I am afraid that it could potentially break all workflows using haskell/actions/setup to set the default ghc

Not sure about that, other workflows seems to be running with the right ghc version:
* https://github.com/haskell/haskell-language-server/runs/3607611296?check_suite_focus=true
* https://github.com/haskell/haskell-language-server/runs/3608714531?check_suite_focus=true

**Comment by jneira** [comment]
* [I've printed the PATH](https://github.com/jneira/haskell-language-server/runs/3609334420?check_suite_focus=true) as suggested by @hasufell to help debug the problem:

`/home/runner/.ghcup/bin:/opt/ghc/8.8.4/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

**Comment by jneira** [comment]
Thanks to @hasufell a possible diagnostic would be:
* the `$PATH` already had `/home/runner/.ghcup/bin` before `/opt/ghc/${ghcVersion}/bin`
* but before the change in https://github.com/actions/virtual-environments/pull/4043 there was no ghc in that directory, so haskell actions used the hvr/ppp

I think 

> The fix could be make the action be in sync with upstream and use ghcup as unique or first installation method

as we had to remove hvr/ppp anyways, as it is no being updated from long time ago

**Comment by jared-w** [comment]
Alrighty, this should be fixed now. 

(As a note to myself: It's past due to make the bundling part of the CI process instead of the local dev process and make the version bumping a CI thing as well)

**Comment by hasufell** [comment]
Does this fix need a new tag or will it be written to the existing tag?

**Comment by jared-w** [comment]
It should be written to v1, v1.2, and v1.2.6

(sorry, I didn't see this message until now)
