### ISSUE TITLE
Linker errors with GHC 7.10.3

### ISSUE THREAD

**Issue by sjakobi** [haskell/actions#79]
GHC 7.10.3 from GHCup has a bug resulting in linker errors, as seen for example in https://github.com/quchen/prettyprinter/runs/4080237799?check_suite_focus=true.

The GHCup issue was reported in https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/123.

AFAIK ghc-7.10.3 from HVR's PPA is patched. Could the setup be fixed to install 7.10.3 from that PPA instead?

Alternatively, some documentation on how to work around this issue would be very helpful.

**Comment by ncaq** [comment]
I had the same problem and solved it by using ubuntu-18.04, which is the older ubuntu in this version.

**Comment by hasufell** [comment]
> Alternatively, some documentation on how to work around this issue would be very helpful.

From the same issue you linked: https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/123#note_346066

**Comment by sjakobi** [comment]
> > Alternatively, some documentation on how to work around this issue would be very helpful.
> 
> From the same issue you linked: https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/123#note_346066

This didn't work for me in https://github.com/quchen/prettyprinter/pull/212/commits/88361f954f5b7ce310c26ac262bfdfc4258e75b5.

**Comment by hasufell** [comment]
> This didn't work for me in quchen/prettyprinter@88361f9.

https://github.com/quchen/prettyprinter/runs/4080227034?check_suite_focus=true

looks to me that worked.

**Comment by sjakobi** [comment]
Ah, yes, I misremembered the problem. Indeed the 7.10.3 job was fixed, but the added ghc-options broke the job using GHC 9.0.1.
