### ISSUE TITLE
[RFC] Statically Linked Binaries

### ISSUE THREAD

**Issue by hazelweakly** [haskell/actions#9]
See https://github.com/actions/setup-haskell/issues/31 for historical context

Tagging all the people tagged in last issue: @chshersh @vrom911 @bubba @utdemir @hasufell

The purpose of opening up this issue is part of migrating other open issues from the old repo to this one. But if anyone has any cool ideas on making this more out of the box, I'd be welcome to hearing them.

**Comment by jared-w** [comment]
As for some new ideas I've had...

It should be well within the scope of the `haskell/actions` repo to have a separate action that is a container action. The container action could certainly be used to get static binaries working on linux. It doesn't eliminate the duplication required for getting static binaries done on windows + macOS + linux, but it could certainly be used to help package up things like static-haskell-nix, musl-ghc, or other projects in a more easily consumable way (in github actions, at least).

The crazier idea I had was to see if it's possible to pull down the alpine bindist for GHC with ghcup, install the musl libraries natively on ubuntu (in github actions), and see if we can get GHC working that way. If I can wrap that up in a clean enough manner, it would mean `static: true` in the haskell setup action could be truly implemented, which would be quite fun, I think.

**Comment by andreasabel** [comment]
No progress on this issue, so I am closing it.  (Not wanting to migrate it once more to the new home of the setup action at https://github.com/haskell-actions/setup.)
